version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE_USER_PASSWORD}
      - POSTGRES_USER=${POSTGRES_DATABASE_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}